root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/main.exe ./cmd/server"
include_ext = ["go"]
exclude_dir = ["vendor", "tmp"]
exclude_regex = [".*_test.go"]
delay = 1000

[run]
cmd = "cmd /c .\\tmp\\main.exe"

[log]
time = true
color = true
